version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Add your build steps here, such as installing dependencies and running tests
      - run:
          name: Install dependencies
          command: npm install

      # Example: Running tests
      - run:
          name: Run tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Install any necessary dependencies for deployment (e.g., SSH client)
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Deploy to EC2 via SSH
      - run:
          name: Deploy to EC2
          command: ssh -i ~/.ssh/id_rsa ec2-user@18.209.24.79 ls -l

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
