version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Add your build steps here, such as installing dependencies and running tests
      - run:
          name: Install dependencies
          command: npm install

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      
      - run:
          name: Log SSH_PRIVATE_KEY
          command: echo "$SSH_PRIVATE_KEY"

       # Create SSH directory and set up SSH key
      - run:
          name: Set up SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pem
            chmod 600 ~/.ssh/id_rsa.pem

      # Start SSH-Agent and add SSH key
      - run:
          name: Start SSH-Agent and add SSH key
          command: |
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_rsa.pem

      # Example SSH command
      - run:
          name: SSH into server
          command: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem ubuntu@ec2-3-90-250-145.compute-1.amazonaws.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
