version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Add your build steps here, such as installing dependencies and running tests
      - run:
          name: Install dependencies
          command: npm install

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      
      - run:
          name: Log SSH_KEY
          command: echo "$SSH_KEY"

      - run:
          name: Copy SSH key to new file
          command: cp "$SSH_KEY" ~/.ssh/id_rsa.pem

      # Set permissions for the copied SSH key file
      - run:
          name: Set permissions for SSH key file
          command: chmod 600 ~/.ssh/id_rsa.pem

      # Deploy to EC2 via SSH
      - run:
          name: Deploy to EC2
          command: ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa.pem ubuntu@ec2-54-227-8-167.compute-1.amazonaws.com ls -l



workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
