version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  deploy:
    docker: 
      - image: circleci/node:14

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:UZw06uGTlEEK7rqgUWWc3OzGK4FshF2qTwQiheyEc10"

      - run:
          name: Deploy Application
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              echo "$SSH_KEY" > ~/.ssh/key.pem
              chmod 400 ~/.ssh/key.pem
              ssh -i ~/.ssh/key.pem ec2-user@54.161.141.123 '\<<EOF
              git pull origin main
              npm install
              npm run build
              pm2 restart your-app
              EOF'
            else
              echo "Skipping deployment for branch $CIRCLE_BRANCH"
            fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main