version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Add your build steps here, such as installing dependencies and running tests
      - run:
          name: Install dependencies
          command: npm install

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run:
          name: Log NODE_KEY
          command: echo "$NODE_KEY"
      # Deploy to EC2 via SSH
      - run:
          name: Set SSH key permissions
          command: echo "$NODE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - run:
          name: Deploy to EC2
          command: ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa ubuntu@ec2-18-209-24-79.compute-1.amazonaws.com ls -l


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
